<%@ page contentType="text/html;charset=UTF-8" language="java" %><%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<c:set var="pageTitle" value="Payments"/><jsp:include page="/WEB-INF/views/common/header.jsp"/>
<section class="page-hero compact"><div class="container"><span class="eyebrow">FINANCIAL CONTROL</span><h1>Payments, invoices & refunds</h1><p>Traceable financial records are never physically erased.</p></div></section>
<div class="container py-5">
<c:if test="${sessionScope.authUser.roleCode == 'CUSTOMER'}"><div class="panel-card mb-4"><h4>Bookings ready for payment</h4><div class="row g-2"><c:forEach items="${bookings}" var="b"><c:if test="${b.status == 'CONFIRMED'}"><div class="col-md-6"><div class="d-flex justify-content-between align-items-center border rounded p-3"><div><strong>${b.bookingRef}</strong><div class="small text-muted">${b.eventType} · LKR ${b.totalAmount}</div></div><a class="btn btn-sm btn-warning" href="${pageContext.request.contextPath}/payments?view=pay&bookingId=${b.bookingId}">Pay</a></div></div></c:if></c:forEach></div></div></c:if>
<div class="panel-card mb-4"><h4>Transaction history</h4><div class="table-responsive"><table class="table align-middle"><thead><tr><th>Reference</th><th>Booking</th><th>Amount</th><th>Method</th><th>Status</th><th></th></tr></thead><tbody><c:forEach items="${payments}" var="p"><tr><td>${p.paymentRef}</td><td>#${p.bookingId}</td><td>LKR ${p.amount}</td><td>${p.method}</td><td><span class="status-badge status-${p.status}">${p.status}</span></td><td><c:if test="${p.status == 'PAID' || p.status == 'REFUNDED'}"><a class="btn btn-sm btn-outline-dark" href="${pageContext.request.contextPath}/payments?view=invoice&paymentId=${p.paymentId}">Invoice</a></c:if><c:if test="${p.status == 'PAID' && sessionScope.authUser.roleCode == 'CUSTOMER'}"> <a class="btn btn-sm btn-outline-warning" href="${pageContext.request.contextPath}/payments?view=refund&paymentId=${p.paymentId}">Refund</a></c:if></td></tr></c:forEach><c:if test="${empty payments}"><tr><td colspan="6"><div class="empty-state">No transactions yet.</div></td></tr></c:if></tbody></table></div></div>
<div class="panel-card"><h4>Refunds</h4><div class="table-responsive"><table class="table"><thead><tr><th>Reference</th><th>Payment</th><th>Amount</th><th>Reason</th><th>Status</th><th></th></tr></thead><tbody><c:forEach items="${refunds}" var="r"><tr><td>${r.refundRef}</td><td>#${r.paymentId}</td><td>LKR ${r.amount}</td><td><c:out value="${r.reason}"/></td><td><span class="status-badge">${r.status}</span></td><td><c:if test="${r.status == 'PENDING' && (sessionScope.authUser.roleCode == 'OPERATIONS_MANAGER' || sessionScope.authUser.roleCode == 'SYSTEM_ADMIN')}"><form method="post" action="${pageContext.request.contextPath}/payments" class="d-flex gap-1"><input type="hidden" name="action" value="refund-process"><input type="hidden" name="refundId" value="${r.refundId}"><input type="hidden" name="simulation" value="SUCCESS"><input type="hidden" name="note" value="Reviewed in demo workflow"><button class="btn btn-sm btn-success" name="decision" value="APPROVE">Approve</button><button class="btn btn-sm btn-outline-danger" name="decision" value="REJECT">Reject</button></form></c:if></td></tr></c:forEach></tbody></table></div></div>
</div>
<jsp:include page="/WEB-INF/views/common/footer.jsp"/>
