<%@ page contentType="text/html;charset=UTF-8" language="java" %><%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<c:set var="pageTitle" value="Manage Schedule"/><jsp:include page="/WEB-INF/views/common/header.jsp"/>
<div class="container py-5 narrow"><div class="panel-card"><span class="eyebrow">SCHEDULE MANAGEMENT</span><h2 class="mt-2">${empty schedule ? 'Create event schedule' : 'Update / reassign event'}</h2><form method="post" action="${pageContext.request.contextPath}/schedule" class="row g-3">
<input type="hidden" name="id" value="${empty schedule ? 0 : schedule.scheduleId}">
<div class="col-12"><label class="form-label">Confirmed booking</label><c:choose><c:when test="${not empty schedule}"><input type="hidden" name="bookingId" value="${schedule.bookingId}"><input class="form-control" value="${schedule.bookingRef}" disabled></c:when><c:otherwise><select class="form-select" name="bookingId" required><option value="">Select booking</option><c:forEach items="${bookings}" var="b"><option value="${b.bookingId}">${b.bookingRef} — ${b.eventType} — ${b.eventDate}</option></c:forEach></select></c:otherwise></c:choose></div>
<div class="col-12"><label class="form-label">Photographer</label><select class="form-select" name="photographerId" required><option value="">Select photographer</option><c:forEach items="${photographers}" var="p"><option value="${p.userId}" ${not empty schedule && schedule.assignedPhotographerUserId == p.userId ? 'selected' : ''}><c:out value="${p.fullName}"/></option></c:forEach></select><div class="form-text">The server validates availability and overlapping active assignments.</div></div>
<div class="col-md-4"><label class="form-label">Date</label><input class="form-control" type="date" name="eventDate" value="${schedule.eventDate}" required></div><div class="col-md-4"><label class="form-label">Start</label><input class="form-control" type="time" name="startTime" value="${schedule.startTime}" required></div><div class="col-md-4"><label class="form-label">End</label><input class="form-control" type="time" name="endTime" value="${schedule.endTime}" required></div>
<div class="col-12"><label class="form-label">Venue</label><input class="form-control" name="venue" value="<c:out value='${schedule.venue}'/>" required></div><div class="col-12"><label class="form-label">Timeline / notes</label><textarea class="form-control" rows="4" name="timeline"><c:out value="${schedule.timeline}"/></textarea></div>
<c:if test="${not empty schedule}"><div class="col-12"><label class="form-label">Reason for change</label><input class="form-control" name="reason" placeholder="Required for traceable schedule changes" required></div></c:if>
<div class="col-12 d-flex gap-2"><button class="btn btn-warning">${empty schedule ? 'Create schedule' : 'Save changes'}</button><a class="btn btn-outline-secondary" href="${pageContext.request.contextPath}/schedule">Cancel</a></div></form>
<c:if test="${not empty schedule}"><hr><form method="post" action="${pageContext.request.contextPath}/schedule" data-confirm="Archive this schedule?"><input type="hidden" name="action" value="archive"><input type="hidden" name="id" value="${schedule.scheduleId}"><div class="input-group"><input class="form-control" name="reason" placeholder="Archive reason" required><button class="btn btn-outline-danger">Archive schedule</button></div></form></c:if>
</div></div>
<jsp:include page="/WEB-INF/views/common/footer.jsp"/>
