<%@ page contentType="text/html;charset=UTF-8" language="java" %><%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<c:set var="pageTitle" value="${booking.bookingRef}"/><jsp:include page="/WEB-INF/views/common/header.jsp"/>
<div class="container py-5"><div class="row g-4"><div class="col-lg-8"><div class="panel-card"><div class="d-flex justify-content-between"><div><span class="eyebrow">BOOKING</span><h2>${booking.bookingRef}</h2></div><span class="status-badge status-${booking.status}">${booking.status}</span></div><hr>
<div class="detail-grid"><div><small>Event</small><strong><c:out value="${booking.eventType}"/></strong></div><div><small>Package</small><strong><c:out value="${booking.packageName}"/></strong></div><div><small>Date</small><strong>${booking.eventDate}</strong></div><div><small>Time</small><strong>${booking.startTime} – ${booking.endTime}</strong></div><div><small>Photographer</small><strong><c:out value="${booking.photographerName}"/></strong></div><div><small>Total</small><strong>LKR ${booking.totalAmount}</strong></div><div class="span-2"><small>Venue</small><strong><c:out value="${booking.venue}"/></strong></div></div>
<c:if test="${booking.status == 'PENDING' && sessionScope.authUser.roleCode == 'PHOTOGRAPHER'}"><hr><h5>Respond to request</h5><form method="post" action="${pageContext.request.contextPath}/bookings" class="row g-2"><input type="hidden" name="action" value="decision"><input type="hidden" name="id" value="${booking.bookingId}"><div class="col-md-8"><input class="form-control" name="reason" placeholder="Optional reason / note"></div><div class="col-md-4 d-flex gap-2"><button name="decision" value="ACCEPT" class="btn btn-success flex-fill">Accept</button><button name="decision" value="REJECT" class="btn btn-outline-danger flex-fill">Reject</button></div></form></c:if>
<c:if test="${booking.status == 'PENDING' && sessionScope.authUser.roleCode == 'CUSTOMER'}"><hr><a class="btn btn-outline-dark mb-3" href="${pageContext.request.contextPath}/bookings?view=edit&id=${booking.bookingId}">Edit pending booking</a></c:if><c:if test="${(booking.status == 'PENDING' || booking.status == 'CONFIRMED') && sessionScope.authUser.roleCode == 'CUSTOMER'}"><hr><h5>Cancel booking</h5><form method="post" action="${pageContext.request.contextPath}/bookings" data-confirm="Cancel this booking?" class="d-flex gap-2"><input type="hidden" name="action" value="cancel"><input type="hidden" name="id" value="${booking.bookingId}"><input class="form-control" name="reason" placeholder="Cancellation reason" required><button class="btn btn-outline-danger">Cancel</button></form></c:if>
<c:if test="${booking.status == 'CONFIRMED' && (sessionScope.authUser.roleCode == 'EVENT_COORDINATOR' || sessionScope.authUser.roleCode == 'OPERATIONS_MANAGER' || sessionScope.authUser.roleCode == 'SYSTEM_ADMIN')}"><hr><form method="post" action="${pageContext.request.contextPath}/bookings" data-confirm="Mark event completed?"><input type="hidden" name="action" value="complete"><input type="hidden" name="id" value="${booking.bookingId}"><button class="btn btn-success">Mark event completed</button></form></c:if>
<c:if test="${booking.status == 'CONFIRMED' && sessionScope.authUser.roleCode == 'CUSTOMER'}"><hr><a class="btn btn-warning" href="${pageContext.request.contextPath}/payments?view=pay&bookingId=${booking.bookingId}">Pay for booking</a></c:if>
<c:if test="${booking.status == 'COMPLETED' && sessionScope.authUser.roleCode == 'CUSTOMER'}"><hr><a class="btn btn-dark" href="${pageContext.request.contextPath}/complaints?view=review&bookingId=${booking.bookingId}">Leave review</a></c:if>
</div></div><div class="col-lg-4"><div class="panel-card"><h4>Status history</h4><div class="timeline"><c:forEach items="${history}" var="h"><div class="timeline-item"><strong>${h[1]}</strong><small>${h[3]}</small><p><c:out value="${h[2]}"/></p></div></c:forEach></div></div></div></div></div>
<jsp:include page="/WEB-INF/views/common/footer.jsp"/>
