db.url=jdbc:sqlserver://localhost:1433;databaseName=PIXORA_DB;encrypt=true;trustServerCertificate=true;sendTimeAsDatetime=false
db.username=sa
db.password=Pixora@2026
db.driver=com.microsoft.sqlserver.jdbc.SQLServerDriver

app.advancePaymentPercent=30
app.galleryRetentionDays=90
app.maxPhotoSizeMb=8
app.maxEvidenceSizeMb=5
app.complaintEscalationHours=48
app.uploadRoot=${user.home}/pixora_uploads


# Google OAuth


google.clientId=368314306904-fc3bbhr9kcfq173fjk5m0ndnqmet428i.apps.googleusercontent.com
google.clientSecret=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
google.redirectUri=http://localhost:8081/pixora_war/auth/google/callback
